spring:
  application:
    name: sakila_project
    request:
      codeLength: 6
      expirationTime: 2
  config:
    import: file:src/main/resources/config/application-secrets.yml
  datasource:
    tokens:
      url: jdbc:mysql://localhost:3307/jwt_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
    sakila:
      url: jdbc:mariadb://localhost:3306/sakila
      driver-class-name: org.mariadb.jdbc.Driver
      dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    show-sql: true
  security:
    jwt:
      token:
        expirationMs: 60000
      refresh:
        expirationMs: 180000
  email:
    port: 587
    host: smtp.gmail.com
    transportProtocol: smtp
    smtpAuth: true
    tlsEnabled: true
    debug: true
  redis:
    primary:
      host: localhost
      port: 6379
